export const menuItemsData = [
  {
    id: 1,
    name: 'رست بیف برگر با پنیر',
    info: 'کاهو-سالاد ماکارونی-خیار-ذرت-زیتون سیاه-گوجه گیلاسی-فیله مرغ-کلم قرمز-هویج-کاپریس',
    price: 77,
    img: '/images/bigBurger.png',
  },
  {
    id: 2,
    name: 'آلفردو فرایزر با سس مخصوص',
    info: 'کاهو-سالاد ماکارونی-خیار-ذرت-زیتون سیاه-گوجه گیلاسی-فیله مرغ-کلم قرمز-هویج-کاپریس',
    price: 27,
    img: '/images/bowl1.png',
  },
  {
    id: 3,
    name: 'سالاد شف',
    info: 'کاهو-سالاد ماکارونی-خیار-ذرت-زیتون سیاه-گوجه گیلاسی-فیله مرغ-کلم قرمز-هویج-کاپریس',
    price: 24,
    img: '/images/bowl2.png',
  },
  {
    id: 4,
    name: 'نیویورک فرایز',
    info: 'کاهو-سالاد ماکارونی-خیار-ذرت-زیتون سیاه-گوجه گیلاسی-فیله مرغ-کلم قرمز-هویج-کاپریس',
    price: 24,
    img: '/images/bowl3.png',
  },
  {
    id: 5,
    name: ' اکسنریم به همراه سیب سوخاری',
    info: 'کاهو-سالاد ماکارونی-خیار-ذرت-زیتون سیاه-گوجه گیلاسی-فیله مرغ-کلم قرمز-هویج-کاپریس',
    price: 24,
    img: '/images/bowl4.png',
  },
  {
    id: 6,
    name: 'سیب سوخاری',
    info: 'کاهو-سالاد ماکارونی-خیار-ذرت-زیتون سیاه-گوجه گیلاسی-فیله مرغ-کلم قرمز-هویج-کاپریس',
    price: 24,
    img: '/images/fruits.png',
  },
  {
    id: 7,
    name: 'سالاد بیکن تخم مرغ',
    info: 'کاهو.بیکن.تخم مرغ.پنیر پارمزان.کاهو فرانسوی',
    price: 24,
    img: '/images/granola cereal bowl.png',
  },
  {
    id: 8,
    name: 'سالاد اسفناج انار',
    info: 'اسفناج-گردو-مغز آفتابگردان-انار-فیله پرتقال',
    price: 24,
    img: '/images/kisspng-aa-na-tigela-smoothie-aa-palm-bowl-apple-j-goji-berry-5b306ffe7baf07.9992682215299010545066.png',
  },
  {
    id: 9,
    name: 'سالاد سزار ',
    info: 'میگو سوخاری. کاهو .زیتون سیاه .نان سیر. پنیر پارمزان .گوجه گیلاسی',
    price: 24,
    img: '/images/kisspng-aa-na-tigela-smoothie-breakfast-juice-health-s-acai-bowl-5b11d2604db908.6695630315278946243184.png',
  },
  {
    id: 10,
    name: 'پارمزان',
    info: 'سیب زمینی سرخ کرده، پنیر پارمزان، سس مک دونالد',
    price: 24,
    img: '/images/kisspng-breakfast-cereal-pizza-muesli-meze-vegetarian-cuis-granola-5ac48d852aeb69.1891892315228307251758.png',
  },
  {
    id: 11,
    name: 'نان سیر',
    info: 'خمیر مخصوص - سس مخصوص - پنیر - 7 تکه انگشتی 30 سانت',
    price: 24,
    img: '/images/kisspng-cuisine-of-hawaii-l-l-hawaiian-barbecue-shrimp-gam-frozen-chicken-5b1e62f3a9e035.2766282415287180676958.png',
  },
  {
    id: 12,
    name: 'سالاد چیکن سزار',
    info: 'کاهو-زیتون سیاه- ذرت-گوجه گیلاسی - فیلی مرغ گریل- نان کورتون- پنیر پارمسان',
    price: 24,
    img: '/images/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22.821205431519651355482.png',
  },
  {
    id: 13,
    name: 'سالاد فصل',
    info: 'کاهو، خیار، گوجه، هویچ رنده شده، سس رنچ',
    price: 24,
    img: '/images/kisspng-greek-salad-fruit-salad-spinach-salad-muesli-vegetable-salad-5a96f429ce9af3.7299622115198423458463.png',
  },
  {
    id: 14,
    name: 'چیز استیک برگر',
    info: 'گوشت95%-استیک خردشده- پنیر زرد و سفید- سس مخصوص- کاهو و گوجه',
    price: 24,
    img: '/images/kisspng-hamburger-street-food-seafood-fast-food-delicious-food-5a75083cceaf41.2676743415176192608466.png',
  },
  {
    id: 15,
    name: 'سالاد',
    info: 'کاهو-سالاد ماکارونی-خیار-ذرت-زیتون سیاه-گوجه گیلاسی-فیله مرغ-کلم قرمز-هویج-کاپریس',
    price: 24,
    img: '/images/kisspng-israeli-salad-european-cuisine.png',
  },
  {
    id: 16,
    name: 'پیتزا سوپریم کراست سوسیس',
    info: 'نان پیتزا-سس مخصوص-کالباس -کوکتل پنیر-کوکتل ژاپنی-پنیر پیتزا-قارچ-ذرت-فلفل سبز',
    price: 24,
    img: '/images/kisspng-italian-cuisine-pizza-pasta-food-plate-healthy-food-5abb864701e2b7.3892346415222390470077.png',
  },
  {
    id: 17,
    name: 'پیتزا',
    info: 'نان پیتزا-سس مخصوص-کالباس -کوکتل پنیر-کوکتل ژاپنی-پنیر پیتزا-قارچ-ذرت-فلفل سبز',
    price: 24,
    img: '/images/pizza.png',
  },
]
